version: '2'

services:

  wordpress:
    image: wordpress:php5.6
    depends_on:
      - mysql
    ports:
      - 80:80
    volumes:
      - ./html-global-lang-attribute:/var/www/html/wp-content/plugins/html-global-lang-attribute
      - ./wp-data:/var/www/html
      - ./includes/docker-scripts:/docker-scripts
    environment:
      # WORDPRESS_DB_HOST: # ... (defaults to the IP and port of the linked mysql container)
      # WORDPRESS_DB_USER: # ... (defaults to "root")
      WORDPRESS_DB_PASSWORD: root_password # (defaults to the value of the MYSQL_ROOT_PASSWORD environment variable from the linked mysql container)
      # WORDPRESS_DB_NAME: # ... (defaults to "wordpress")
      WORDPRESS_TABLE_PREFIX: wp_ # ... (defaults to "", only set this when you need to override the default table prefix in wp-config.php)

  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root_password

  #phpmyadmin:
  #  image: phpmyadmin/phpmyadmin
  #  links:
  #    - mysql:db
  #  ports:
  #    - 8181:80
  #  environment:
  #    MYSQL_USERNAME: root
  #    MYSQL_ROOT_PASSWORD: root_password
